* My Emacs config

This is a new repo with my emacs config converted from [[https://github.com/radian-software/straight.el][straight]] to [[https://github.com/progfolio/elpaca][elpaca]]. It's kind of a constant work in progress. While switching to elpaca, I decided to switch from helm-bibtex to citar, and that isn't quite done. There are some other little things that I tried to clean up while converting that also aren't done.

** Problems

- How can I get ob-lilypond to fontify properly?

** Some neat things

*** NixOS and vterm

On NixOS, it's best to let Nix take care of compiling the vterm module. Since it's already there, we don't want elpaca to download it again and try to compile it. The following macro allows elpaca to take care of it when it isn't installed, but otherwise stops elpaca from trying to install it even as a dependency (like when installing vterm-toggle).

#+begin_src elisp
(defmacro ide/elpaca-use-package (package &rest body)
  (if (locate-library (symbol-name `,package))
      `(progn
	     (cl-pushnew (quote ,package) elpaca-ignored-dependencies)
	     (elpaca-use-package ,package :ensure nil ,@body))
    `(elpaca-use-package ,package ,@body)))

(ide/elpaca-use-package vterm :defer t)
#+end_src

*** use-package in Emacs 29

As of Emacs 29, =use-package= is built in. This snippet only installs it when the function doesn't already exist.

#+begin_src elisp
(unless (fboundp 'use-package)
  (elpaca use-package (require 'use-package)))
#+end_src

